
services:
  - type: web
    name: lybot-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PINECONE_API_KEY
        sync: false
